'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export default function AccountSecurityPage() {
  const [factorId, setFactorId] = useState('')
  const [qr, setQr] = useState('')
  const [secret, setSecret] = useState('')
  const [code, setCode] = useState('')
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [ready, setReady] = useState(false)
  useEffect(() => {
    const db = createClient()
    void (async () => {
      const { data: { user } } = await db.auth.getUser()
      if (!user) { location.replace('/login'); return }
      const { data: level } = await db.auth.mfa.getAuthenticatorAssuranceLevel()
      if (level?.currentLevel === 'aal2') { location.replace('/admin'); return }
      const { data, error } = await db.auth.mfa.listFactors()
      if (error) { setMessage('認証設定を取得できません。再読み込みしてください'); return }
      const factor = data.totp.find(f => f.status === 'verified')
      if (factor) setFactorId(factor.id)
      setReady(true)
    })()
  }, [])
  async function enroll() {
    setBusy(true); setMessage('')
    try {
      const db = createClient()
      // Clear only this user's unfinished TOTP enrollments to allow a safe retry.
      const { data: factors } = await db.auth.mfa.listFactors()
      for (const f of factors?.all ?? []) if (f.factor_type === 'totp' && f.status === 'unverified') await db.auth.mfa.unenroll({ factorId: f.id })
      // 発行者名は英数字にする（日本語だと一部の認証アプリでQR登録に失敗するため）
      const { data, error } = await db.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Kaitori Square', issuer: 'KaitoriSquare' })
      if (error) { setMessage(`登録を開始できません（${error.message}）。再度お試しください`); return }
      setFactorId(data.id); setQr(data.totp.qr_code); setSecret(data.totp.secret)
    } finally { setBusy(false) }
  }
  async function verify() {
    setBusy(true); setMessage('')
    try {
      const db = createClient()
      const { error } = await db.auth.mfa.challengeAndVerify({ factorId, code })
      if (error) {
        setMessage('認証コードが一致しません。アプリに表示されている最新の6桁でお試しください。何度も失敗する場合は、スマホの日時設定が「自動」になっているか確認し、認証アプリ内に古い「買取スクエア/Kaitori Square」の項目が複数あれば削除してからもう一度QRコードを読み取ってください')
        return
      }
      location.replace('/admin')
    } finally { setBusy(false) }
  }
  return <main className="max-w-md mx-auto p-6 space-y-5">
    <h1 className="text-2xl font-bold">二段階認証</h1>
    <p>管理者・マネージャーの操作には、認証アプリの6桁コードが必要です。</p>
    {!ready ? <p>確認中…</p> : !factorId ? <><p>お使いの認証アプリを準備して、登録を始めてください。</p><Button onClick={enroll} disabled={busy}>認証アプリを登録</Button></> : <>
      {qr && <><p>認証アプリ（Google Authenticator等）でQRコードを読み取り、表示された6桁コードを入力してください。</p>{/* QR is generated by Supabase for the current authenticated user. */}<img src={qr} alt="認証アプリ登録用QRコード" className="w-64 h-64 bg-white" />
      {secret && <details className="text-sm text-muted-foreground"><summary className="cursor-pointer">QRコードが読み取れない場合（手動入力）</summary><p className="mt-1">認証アプリの「セットアップキーを入力」で以下のキーを入力してください:</p><p className="mt-1 select-all break-all rounded bg-muted p-2 font-mono">{secret}</p></details>}
      <p className="text-xs text-muted-foreground">※登録をやり直した場合は、認証アプリ内の古い項目を削除してから読み取り直してください（古い項目のコードは使えません）</p></>}
      <label htmlFor="mfa-code">認証コード</label><Input id="mfa-code" autoComplete="one-time-code" inputMode="numeric" value={code} maxLength={6} onChange={e => setCode(e.target.value.replace(/\D/g, ''))} />
      <Button onClick={verify} disabled={busy || code.length !== 6}>認証して管理画面へ</Button>
    </>}
    {message && <p role="alert" className="text-red-600">{message}</p>}
    <Button variant="outline" onClick={async () => { await createClient().auth.signOut(); location.replace('/login') }}>ログアウト</Button>
  </main>
}
