'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

export default function AccountSecurityPage() {
  const [factorId, setFactorId] = useState('')
  const [qr, setQr] = useState('')
  const [code, setCode] = useState('')
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [ready, setReady] = useState(false)
  useEffect(() => {
    const db = createClient()
    void (async () => {
      const { data: { user } } = await db.auth.getUser()
      if (!user) { location.replace('/login'); return }
      const { data: level } = await db.auth.mfa.getAuthenticatorAssuranceLevel()
      if (level?.currentLevel === 'aal2') { location.replace('/admin'); return }
      const { data, error } = await db.auth.mfa.listFactors()
      if (error) { setMessage('認証設定を取得できません。再読み込みしてください'); return }
      const factor = data.totp.find(f => f.status === 'verified')
      if (factor) setFactorId(factor.id)
      setReady(true)
    })()
  }, [])
  async function enroll() {
    setBusy(true); setMessage('')
    try {
      const db = createClient()
      // Clear only this user's unfinished TOTP enrollments to allow a safe retry.
      const { data: factors } = await db.auth.mfa.listFactors()
      for (const f of factors?.all ?? []) if (f.factor_type === 'totp' && f.status === 'unverified') await db.auth.mfa.unenroll({ factorId: f.id })
      const { data, error } = await db.auth.mfa.enroll({ factorType: 'totp', friendlyName: '買取スクエア', issuer: '買取スクエア' })
      if (error) { setMessage('登録を開始できません。再度お試しください'); return }
      setFactorId(data.id); setQr(data.totp.qr_code)
    } finally { setBusy(false) }
  }
  async function verify() {
    setBusy(true); setMessage('')
    try {
      const db = createClient()
      const { error } = await db.auth.mfa.challengeAndVerify({ factorId, code })
      if (error) { setMessage('認証コードが一致しません。新しいコードでお試しください'); return }
      location.replace('/admin')
    } finally { setBusy(false) }
  }
  return <main className="max-w-md mx-auto p-6 space-y-5">
    <h1 className="text-2xl font-bold">二段階認証</h1>
    <p>管理者・マネージャーの操作には、認証アプリの6桁コードが必要です。</p>
    {!ready ? <p>確認中…</p> : !factorId ? <><p>お使いの認証アプリを準備して、登録を始めてください。</p><Button onClick={enroll} disabled={busy}>認証アプリを登録</Button></> : <>
      {qr && <><p>認証アプリでQRコードを読み取り、表示されたコードを入力してください。</p>{/* QR is generated by Supabase for the current authenticated user. */}<img src={qr} alt="認証アプリ登録用QRコード" className="w-64 h-64 bg-white" /></>}
      <label htmlFor="mfa-code">認証コード</label><Input id="mfa-code" autoComplete="one-time-code" inputMode="numeric" value={code} maxLength={6} onChange={e => setCode(e.target.value.replace(/\D/g, ''))} />
      <Button onClick={verify} disabled={busy || code.length !== 6}>認証して管理画面へ</Button>
    </>}
    {message && <p role="alert" className="text-red-600">{message}</p>}
    <Button variant="outline" onClick={async () => { await createClient().auth.signOut(); location.replace('/login') }}>ログアウト</Button>
  </main>
}
